- name: 搭配 Kubernetes 的 ACS
  href: ./index.yml
- name: 概觀
  items:
    - name: 有關 Container Service
      href: container-service-intro-kubernetes.md
- name: 快速入門
  expanded: true
  items:
    - name: Kubernetes Linux
      href: container-service-kubernetes-walkthrough.md
- name: 教學課程
  items:
    - name: 1 - 建立容器映像
      href: container-service-tutorial-kubernetes-prepare-app.md
    - name: 2 - 建立容器登錄
      href: container-service-tutorial-kubernetes-prepare-acr.md
    - name: 3 - 建立 Kubernetes 叢集
      href: container-service-tutorial-kubernetes-deploy-cluster.md
    - name: 4 - 執行應用程式
      href: container-service-tutorial-kubernetes-deploy-application.md
    - name: 5 - 調整應用程式
      href: container-service-tutorial-kubernetes-scale.md
    - name: 6 - 更新應用程式
      href: container-service-tutorial-kubernetes-app-update.md
    - name: 7 - 透過 OMS 進行監視
      href: container-service-tutorial-kubernetes-monitor.md
- name: 範例
  items:
    - name: Azure CLI
      href: cli-samples.md
- name: 概念
  items:
    - name: 安全容器
      href: container-service-security.md
    - name: 服務主體 - Kubernetes
      href: container-service-kubernetes-service-principal.md
- name: 使用說明指南
  items:
    - name: Kubernetes 搭配 Windows 快速入門
      href: container-service-kubernetes-windows-walkthrough.md
    - name: 容器管理 - Kubernetes UI
      href: container-service-kubernetes-ui.md
    - name: 部署 Helm 圖表
      href: container-service-kubernetes-helm.md
    - name: 搭配 Kubernetes 和 Jenkins 的 CI/CD
      href: container-service-kubernetes-jenkins.md
    - name: 使用 Draft 搭配 ACR 和 ACS
      href: container-service-draft-up.md
    - name: 與 ACS 叢集連接
      href: container-service-connect.md
    - name: 調整 ACS 叢集的規模
      href: container-service-scale.md
    - name: 監視
      items:
        - name: 透過 Datadog 進行監視
          href: container-service-kubernetes-datadog.md
        - name: 透過 Sysdig 進行監視
          href: container-service-kubernetes-sysdig.md
        - name: 透過 CoScale 進行監視
          href: container-service-kubernetes-coscale.md
    - name: 部署 Spring Boot 應用程式
      items:
        - name: 將 Spring Boot 應用程式部署到 Azure Container Service 中的 Linux
          href: container-service-deploy-spring-boot-app-on-linux.md
        - name: 將 Spring Boot 應用程式部署到 Azure Container Service 中的 Kubernetes 叢集
          href: container-service-deploy-spring-boot-app-on-kubernetes.md
- name: 參考
  items:
    - name: Azure CLI 2.0
      href: /cli/azure/acs
    - name: REST
      href: /rest/api/compute/containerservices
- name: 資源
  items:
    - name: Azure 藍圖
      href: 'https://azure.microsoft.com/roadmap/'
    - name: 常見問題集
      href: container-service-faq.md
    - name: 範本 - ACS 引擎
      href: 'https://github.com/Azure/acs-engine'
    - name: 價格
      href: 'https://azure.microsoft.com/pricing/details/container-service/'
    - name: 區域可用性
      href: 'https://azure.microsoft.com/regions/services/'
    - name: 堆疊溢位
      href: 'http://stackoverflow.com/questions/tagged/azure-container-service'
    - name: 影片
      href: 'https://azure.microsoft.com/resources/videos/index/?services=container-service&sort=newest'